### ISSUE TITLE
work around OSX finder "zip implementation"

### ISSUE THREAD

**Issue by DeepDiver1975** [McNetic/PHPZipStreamer#16] opened 2014-10-16 13:14 UTC
THX

**Comment by McNetic** [comment] 2015-04-20 14:56
I had a look at the problem in an OSX VM myself, and also found some other resources complaining about the same OSX incompatibilities, and I have come to the conclusion that the OSX finder is obviously not able to handle streamed zip files (general purpase flag bit 3, part of the official zip standard since 1993).
As I can't fix this problem without fundamentally changing the assumptions ZipStreamer is working on (any stream, not necessarily seek()able), I will close this as wontfix. I might however add an option to provide file size and crc from outside of zipstreamer, so it can stream a zip file without doing seek() on it's own, to be able to work around the issues in OSX.

**Closed by McNetic** 2015-04-20 14:56 UTC

**Comment by jens-maus** [comment] 2015-04-20 15:08
This sounds like a goo compromise. Looking forward to seeing that version.

**Comment by alkivi-sas** [comment] 2015-05-12 14:37
Any news about this option ? It would be very useful for us :)

**Comment by McNetic** [comment] 2015-05-12 15:19
I did not get any feedback in owncloud/core#10001. There won't be any updates here, anyways (I'd open a new issue if to implement the new features set).

**Comment by peeech** [comment] 2015-08-13 21:02
Hello, I have been digging through this issue a bit and found some threads that claim that Archive Utility would be able to open zip file with bit3 != 0:

if (bit3 and compression equals 8) {
 // expect data descriptor after content
}

Here is the full thread:
https://github.com/archiverjs/node-zip-stream/issues/8

I tried ZipStreamer with settings ['zip64' => false, 'compress' => COMPR::DEFLATE, 'level' => COMPR::NORMAL]. Unfortunately created zip is still not recognized by Mac's Archive Utility. Assuming that conclusions of the above thread are valid what would be the way to obtain a zip file with "bit3 and compression equals 8" characteristics with ZipStream?

**Comment by McNetic** [comment] 2015-08-14 07:32
We tried all possible combinations :-(.
Always when someone finds some new mentions of the problem and possible solutions, I dig through all linked ressources (often finding it boiling down to the same sources), to see if there is another option we did not already try. I found the linked issue a bit confusing as to if they found a solution or not, but finally saw the issue was in fact closed as "platform bug, wontfix". So they seem to have come to the same conclusion as we.

**Comment by jens-maus** [comment] 2015-08-14 09:03
Sorry, but I still feel I have to comment on that OSX<>zip issue here again. As some might know, I have at least been able to work around that issue using the changes documented in my pull request (https://github.com/McNetic/PHPZipStreamer/pull/19). With these changes fully OS X compatible zip files are generated – even in owncloud!

I know that PHPZipStreamer is targeted to providing a fully streamable interface (because this is more convenient and faster), but as many of you have found out yourself, the OS X zip utilities are unfortunately not able to extract data generated by PHPZipStreamer. Therefore, as a *workaround* I have added some functionality to PHPZipStreamer that enabled it to generate proper OS X compatible zip files. Unfortunately, this workaround disables the streamable interface of PHPZipStreamer because it uses fseek() to generate a properly OS X compatible zip. I also fully understand that this is against the fundamental idea of PHPZipStreamer. However, as PHPZipStreamer is used in owncloud for years and that OS X zip support is therefore broken in owncloud for years I still feel that my workaround would at least be worth an integration for the rare cases where OS X compatibility is definitely required (owncloud).

Here I have my version of PHPZipStreamer running in ownCloud 8 without any issues and it generates zip files that can be perfectly used in an OS X environment.

Thus, I really feel that the owncloud developers could at least consider using my version of PHPZipStreamer and integrate a check if OS X is the target platform for the download and then use the non-streamed interface of PHPZipStreamer instead of always generating zip files that cannot be unarchived on OS X because OS X unfortunately doesn't support the latest zip extensions PHPZipStreamer requires.

Unfortunately the owncloud developers have closed the corresponding discussion (https://github.com/owncloud/core/issues/10001) to collaborators, so I cannot join the discussion there and suggest to at least integrate my changes as a workaround as long as OS X is known to not support the zip format PHPZipStreamer is generating per default.

**Comment by McNetic** [comment] 2015-08-17 07:32
Well, I think this is the wrong place to try get into the discussion about owncloud. Appearently, the owncloud folks seem to have decided on a different approach (tar) to fix the issues with OSX (see the mentioned owncloud ticket).

Also, I don't like how this issue keeps presenting itself as an owncloud or zipstreamer bug: The bug is actually in OSX. It's not apple not supporting "the latest zip extensions". It's apple ignoring parts of the zip standard at least as old as 2005 (Zip64) and 1993 (streamed zip), that (on top) would cost them half a day of software engineering to implement (zilch for the command line, as they package a long long outdated version of a tool that could simply have been updated). They also got at least one bug report about the whole fiasco more than a year ago (I might suspect they got earlier ones), and decided to ignore it.

Before Windows XP, every windows user had to install a third party tool to use zip files. Now maybe Mac users have to.

**Comment by jens-maus** [comment] 2015-08-17 07:58
I fully agree that of course Apple has to be blamed for the root cause of the issue PHPZipStreamer is fighting so long with. And, of course, I never meant to blame PHPZipStreamer and it would be Apples' responsibility to ensure their ZIP support is perfect and according to common standards. But as happened often in history with others things I think you can blame the bad guys at Apple as much as you can, the only thing that matters is really how the users of PHPZipStreamer (and in that specific case 'owncloud')  can USE your software. And in fact for an end user the ZIP support seems to be broken when using any software using PHPZipStreamer on a MacOSX clients. That's why I still think a workaround (even if not technically perfect and even if it would make you feel sick) would be the better approach than forcing your users to implement workarounds themselves.

And if Mac Users wouldn't be able to unarchive zip files at all I would agree with you that one simply had to instruct OSX users to install the right third-party tools. But as a matter of fact OSX allows to unarchive zip files already, thus ordinary users simply experience that the ZIP files are broken even if that is – technically spoken – not correct.

**Comment by McNetic** [comment] 2015-09-28 10:54
I'm please to tell you that the workaround in owncloud for OSX now seems to be in place: https://github.com/owncloud/core/pull/19318.

**Comment by alicederyn** [comment] 2020-10-29 17:42
I believe you may be able to fix your issue with Mac OS X by preceding your data descriptor with the [optional data descriptor header](https://en.wikipedia.org/wiki/Zip_(file_format)#Data_descriptor), 0x08074b50.

I have posted my analysis in blog format here if you want any more details: https://codingantihero.wordpress.com/2020/10/29/mac-os-x-zip-issue/
